### PR TITLE
open_in_current_term

### PR DESCRIPTION
**Pull request by jamesmcnamara**
Great plugin!

However, I did run into some pain with it, because I like to use terminal-based vim.

So I added a configuration flag that allows you to have your command fed back into your current terminal session if you'd like.

Hope you like it!

### CODE REVIEW

**Comment by mchelem** [comment]
Great addition! I tried this myself in the past without success. Did you manage to open Vim in the same terminal you ctrl + clicked? For me it still doesn't work. 

Could you please share your operating system, Vim and Terminator versions?

**Comment by jamesmcnamara** [comment]
Yeah I use it as part of my daily workflow!

I've tested it with Ubuntu 16.04 + 17.10, Terminator 1.91, Vim 8, NeoVim 0.2, and Nano 2.8.6.

Do you get any errors when you ctrl + click?

**Comment by mchelem** [comment]
@jamesmcnamara Sorry for the ridiculously long delay. I see you closed your PR, do you mind if I still merge your code?

**Comment by jamesmcnamara** [comment]
No go for it!

**Pull request merged**
