### PR TITLE
Only load the plugin config if it exist on config file

### PR DESCRIPTION
**Pull request by hugomaiavieira**
After copy the plugin script to the terminator plugins dir and try to enable it, I get a "TypeError: 'NoneType' object is not iterable" error. This occurs because I do not have the configuration for the plugin on the config file and the script try to load it any way.

### CODE REVIEW

**Comment by fotanus** [comment]
I can reproduce it. This is the traceback:

```
Traceback (most recent call last):
  File "/usr/share/terminator/terminatorlib/prefseditor.py", line 1186, in on_plugin_toggled
    self.registry.enable(plugin)
  File "/usr/share/terminator/terminatorlib/plugin.py", line 140, in enable
    self.instances[plugin] = self.available_plugins[plugin]()
  File "/home/fotanus/.config/terminator/plugins/editor_plugin.py", line 30, in __init__
    self.check_config()
  File "/home/fotanus/.config/terminator/plugins/editor_plugin.py", line 40, in check_config
    config.update(saved_config)
TypeError: 'NoneType' object is not iterable
```
However, I suggest test for NoneType and allow other NoneType exceptions be throw in the future instead of assume that it is because the file does not exist. Not sure if this is usual in python?

**Comment by hugomaiavieira** [comment]
Note sure if this is usual in python too, but I think this is a better solution.

**Comment by hugomaiavieira** [comment]
@fotanus looks good now?

**Comment by fotanus** [comment]
Looks great, except that now it is broke :-)

I got this stack trying to activate the plugin:

```
  File "/usr/share/terminator/terminatorlib/prefseditor.py", line 1186, in on_plugin_toggled
    self.registry.enable(plugin)
  File "/usr/share/terminator/terminatorlib/plugin.py", line 140, in enable
    self.instances[plugin] = self.available_plugins[plugin]()
  File "/home/fotanus/.config/terminator/plugins/editor_plugin.py", line 30, in __init__
    self.check_config()
  File "/home/fotanus/.config/terminator/plugins/editor_plugin.py", line 37, in check_config
    config.update(saved_config)
UnboundLocalError: local variable 'config' referenced before assignment
```
Which makes sense, since you are using `config` on line 37 and defining it on line 39.

**Comment by hugomaiavieira** [comment]
@fotanus shame on me :blush: 

I changed the repo version and tested instead of the `.config/terminator/plugin` one. Besides, I've changed the code without attention (I've stopped a task to do the fix quickly). Anyway, excuses aside, it's ok now?

**Comment by fotanus** [comment]
:+1: It works and fixes the issue. @mchelem, feel free to ship it.

**Pull request merged**
